---
- name: Install Docker Dependencies
  yum:
    name:
      - yum-utils
    state: present

- name: Add Docker Repo
  shell: yum-config-manager --add-repo  https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce-{{ docker_version }}
      - docker-ce-cli-{{ docker_version }}
      - containerd.io
    state: present

- name: Ensure docker config directory
  file:
    path: /etc/docker
    state: directory

- name: Config Docker Daemon
  copy:
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ],
        "registry-mirrors": ["https://2jafvjoh.mirror.aliyuncs.com"]
      }
    dest: /etc/docker/daemon.json
  register: daemonConfig

- name: Start Docker Service
  service:
    name: docker
    state: restarted
    enabled: yes
  when: daemonConfig.changed
